version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: inn_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./:/app
